norm_war_rus = [
    # 'всу',
    'авиационный поддержка',
    'артиллерийский налёт',
    'артиллерийский огонь',
    'атака',
    'атаковать',
    'атаковать группа',
    # 'батальон',
    'бежать',
    # 'боевик',
    'боевой задача',
    'боевой слаживание',
    'боец чвк «вагнер»',
    'бригада',
    'в бой',
    'в результат бой',
    'в ход проведение специальный военный операция',
    'вести бой',
    'вести бой',
    'вести огонь',
    'взятие под контроль',
    'военный положение',
    'военнопленный',
    # 'военнослужащий',
    'военный действие',
    'воздушный тревога',
    # 'войско',
    'войско рф уничтожить',
    'вооружённый формирование украина вфу',
    'воевать',
    'выполнить пуск ракета',
    'группировка войско',
    'действие пехота',
    'демилитаризация',
    # 'денацификация',
    'десантно-штурмовой бригада',
    'диверсионно-разведывательный группа дрг',
    'диверсионный группа',
    'дивизион',
    'доброволец',
    'живой сила и техника противник',
    'защитник',
    'зона спецоперация',
    'из окружение',
    'иностранный наёмник',
    'колонна военный техника',
    'контрбатарейный борьба',
    'контрнаступление',
    'краинский командование',
    'линия боевой соприкосновение',
    'линия оборона',
    'линия фронт',
    # 'личный состав',
    'массировать обстрел',
    'минирование',
    'миномётный расчёт',
    'на данный направление',
    'на передовой',
    # 'на поле бой',
    'наёмник',
    'наёмник киевский режим',
    'накрыть огонь',
    'налёт',
    'нанести ракетный удар по территория',
    'нанести удар',
    'наступать',
    # 'нести потеря',
    'оборонительный порядок',
    'обстрел',
    'обстрелять',
    'огневой поддержка',
    'огневой давление',
    'огневой поражение',
    'огневой позиция',
    'открыть огонь',
    # 'отразить',
    'отряд чвк «вагнер»',
    'первый линия противник',
    'перебрасывать подкрепление',
    'перегруппировка',
    'перейти под контроль',
    'пехота всу',
    'плацдарм для дальнейший наступление',
    'подавление огнев точка',
    'подбить',
    'подвоз боеприпас',
    # 'подразделение',
    'подразделение отступать',
    'получить ранение',
    'понести потеря',
    'поразить подразделение',
    'поразить элемент военный инфраструктура',
    # 'пострадать',
    'потеря противник',
    'преступление',
    'при поддержка артиллерия',
    'применение ракета',
    'продолжить наступление',
    'прорыв оборона',
    'противник',
    'пункт дислокация',
    'пункт дислокация',
    'разведка бой',
    'разведчик',
    'ракетный удар',
    # 'расчёт',
    'расчёт артиллерия',
    # 'российский армия',
    'российский артиллерия',
    'российский войско',
    'российский часть',
    'российский командование',
    # 'рота',
    # 'рубеж',
    'сбить',
    'секретный биолаборатория',
    'сила специальный назначение',
    'скопление живой сила',
    # 'специальный военный операция',
    # 'спецоперация',
    'тактический успех',
    'тероборона',
    'террористический акт',
    'тяжелораненый',
    # 'удар',
    'удар по территория',
    # 'украинский армия',
    'украинский артиллерия',
    'украинский боевик',
    'украинский войско',
    'украинский националист',
    'украинский соединение',
    'украинский формирование',
    'украинский часть',
    'украинский фашист',
    'укрепление противник',
    'укрепрайон',
    'укронацист',
    'унести жизнь',
    'уничтожить',
    'уничтожение наёмник',
    'усиление оборона',
    'ход проведение операция',
    'ход проведение специальный военный операция',
    'ход проведение спецоперация',
    'цель удар',
    'цель удар быть достигнуть',
    # 'штурм',
    'штурмовой отряд',
    'эшелон',
    'зеленск',
    'NHL',
    'FIFA',
    'UEFA',
    'NBA',
    'НХЛ',
    'ФИФА',
    'УЕФА',
    'НБА',
    'мятеж',
    'вагнер',
]

norm_stock_rus = [
    'brent опуститься',
    'brent подорожать',
    'цена нефть brent',
]

norm_war_en = [
    # 'bakhmut',
    'kremlin-backed mercenaries',
    'prigozhin',
    # 'wagner group',
    # 'wagner group mercenary units',
    'air raid siren',
    'bloodshed',
    'buried',
    # 'dead',
    # 'died',
    'drone attacks',
    'injured',
    'injuries',
    # 'killed',
    'killing',
    'missile attack',
    'missile strike',
    'offensive efforts',
    'peace deal',
    'peace plan',
    'russian forces shelled',
    'territorial gains',
    'wounded',
    'russia fired',
    'far-right fighters',
    'the russian strikes',
    'traumatic stress',
    'missile threat',
    'foreign agents',
    'detective story',
    'comedy',
    'archaeology',
    'deporting children',
    'murderer',
    'arrested in protests',

]

norm_stock_en = [
    'euro slides',
    'u.s. stocks',
    'uk stocks',
    'asian shares',
    'asian shares fall',
    'asian stock markets',
    'asian stocks',
    'asian stocks gain',
    'asian stocks rise',
    'asian stocks slip',
    'asian stocks steady',
    'before the bell',
    'euro zone stocks',
    'global markets slide',
    'global stocks',
    'global stocks fall',
    'morning bid',
    'oil rises',
    # 'premarket',
    'stock market updates',
    'stocks gain',
    'stocks moving',
    'nobel Laureate',
    'literature',
    'tokyo stocks',
    'analysis',
    'saddam hussein',
]

norm_en = [
    'ramadan',
    'mosques',
    'breakfast ideas',
    'breakfast recipe',
    'bookmakers',
    "women',s pro soccer",
    'basketball team',
    'soccer league',
    'oil continues slide',
    'oil settles down',
    'stocks making the biggest moves midday',
    'top stock picks',
    'dollar strengthens',
    'north korea missile launch',
    'grand prix',
    'formula one',
    'guest essay',
    'explainer:',
    'bible',
    'portrait',
    'drummer',
    'aspect of culture',
    'pizza',
    'presidential nomination',
    'retirement age',
    'prince harry',
    'museum',
    'school shooter',
    'conspiracy theories',
    'online casino',
    'reporter detained',
    'cricket',
    'baseball',
    'championship'
    'folk tales',
    'love story',
    'filmmaker',
    'musician'
    'acrobats',
    'bicyclists',
    'horseracing',
    'horse racing',
    'incarceration',
    'gwyneth paltrow',
    'trump indicted',
    'tornadoes',
    'cyclone',
    "kim jong un's daughter",
    'cleric',
    'capitol attack',
    'shakespeare',
    'zelensky',
    'NHL',
    'FIFA',
    'UEFA',
    'NBA',
    'rebellion',
    'wagner',
]
